### ISSUE TITLE
OggOpus records in 44.1 kHz but marks file as 48 kHz

### ISSUE THREAD

**Issue by nickbailuc** [SimpleMobileTools/Simple-Voice-Recorder#228] opened 2023-09-29 19:29 UTC
I made many recordings with Opus and 320 kbps, and realized they all sound high pitched (and a bit fast). Importing to Audacity and changing the sample rate to 44.1 fixes the problem. 

Every audio player I've tried including the Simple Voice Recorder's playback of any recorded files sounds high-pitched. 

It seems that the Ogg encoder the player uses encodes (or marks) the files as 48 kHz whereas they are being exported as 44.1 kHz.

The M4A setting does not have this problem, but I like Opus and very happy to see this program supports it.

(P.S. thanks for the great Simple software suite, very much needed in the Android ecosystem!)

**Comment by Aga-C** [comment] 2023-09-29 19:39
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/102.

**Closed** 2023-09-30 18:43 UTC
