### ISSUE TITLE
Feature Request: Add bookmarks while recording

### ISSUE THREAD

**Issue by dotancohen** [SimpleMobileTools/Simple-Voice-Recorder#200] opened 2023-06-18 19:49 UTC
It would be very helpful if one could bookmark timestamps in a recording while recording. This would be handy e.g. when the professor says something important in an hour-long lecture.

**Comment by Aga-C** [comment] 2023-06-18 20:33
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/6.

**Closed** 2023-06-18 21:34 UTC
