### ISSUE TITLE
Edit recordings

### ISSUE THREAD

**Issue by jcperil** [SimpleMobileTools/Simple-Voice-Recorder#172] opened 2022-12-30 15:48 UTC
This is a two part feature request.

1. Ability to trim a short segment of a recording.
2. Ability to remove some segment(s) of a recording.

**Comment by Aga-C** [comment] 2022-12-30 17:29
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Voice-Recorder/issues/40.

**Comment by anaskaejdar** [comment] 2023-07-14 19:58
In addition to trimming and cutting, I propose for consideration the option of recording a new segment at a specific timestamp. That way, if, for example, there was something poorly worded earlier in the recording, the user could remove that bit and replace it with a new take without having to either start over nor wait until they can get to their PC to splice recordings together inside audacity. Also, edit existing voice notes retroactively.

**Comment by RustoMCSpit** [comment] 2023-09-13 11:06
> In addition to trimming and cutting, I propose for consideration the option of recording a new segment at a specific timestamp. That way, if, for example, there was something poorly worded earlier in the recording, the user could remove that bit and replace it with a new take without having to either start over nor wait until they can get to their PC to splice recordings together inside audacity. Also, edit existing voice notes retroactively.

you can append a recording kinda rn, only if it is currently being recorded and you hit the pause button though

**Closed** 2024-04-18 10:08 UTC
Labels: feature request
