### ISSUE TITLE
Bookmark support

### ISSUE THREAD

**Issue by KamalW** [SimpleMobileTools/Simple-Voice-Recorder#180] opened 2023-02-11 03:44 UTC
It would be great if this app has bookmark support.

1. A way to add bookmarks while recording and playback.
2. Import/export bookmarks in a format that will allow easy exchange of bookmarks between other applications.

**Comment by tibbi** [comment] 2023-02-11 17:53
duplicate of #6

**Closed by tibbi** 2023-02-11 17:53 UTC
