### ISSUE TITLE
Add recording file location option in settings.

### ISSUE THREAD

**Issue by stevenleeS0ht** [SimpleMobileTools/Simple-Voice-Recorder#48] opened 2021-02-26 00:17 UTC
Currently, `Simple Voice Recorder` put all recording file under `Music/`. It would be nice to add custom option to choose file location.

**Comment by stevenleeS0ht** [comment] 2021-02-26 03:25
@tibbi , what is your opinion?

**Comment by tibbi** [comment] 2021-02-26 09:06
actually, duplicate of #18

**Closed by tibbi** 2021-02-26 09:06 UTC
Labels: feature request
