### ISSUE TITLE
Simple Voice Recorder doesn't recognize Bluetooth microphone

### ISSUE THREAD

**Issue by Attronarch** [SimpleMobileTools/Simple-Voice-Recorder#56] opened 2021-06-16 12:41 UTC
When I plug in my Bluetooth headset, Simple Voice Record still records phone microphone instead of headset's microphone.

Could you add a feature to change the recording input?

**Comment by tibbi** [comment] 2021-06-16 17:02
duplicate of #27

**Closed by tibbi** 2021-06-16 17:02 UTC
